In [1]:
# import libraries 
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [2]:
# load in data
ps_raw = pd.read_csv(r"PS_2026.04.03_18.36.56.csv", skiprows = 292)
display(ps_raw)

# define only variables of interest
ps = ps_raw[
    [
        "pl_name", # planet name 
        "hostname", # star name 
        "default_flag", # recommended rows for duplicates
        "pl_rade", "pl_radeerr1", "pl_radeerr2", # planet radius 
        "pl_orbper", "pl_orbpererr1", "pl_orbpererr2", # orbital period 
        "pl_eqt", "pl_eqterr1", "pl_eqterr2", # equilibrium temperature 
        "st_teff", "st_tefferr1", "st_tefferr2", # stellar temperature 
        "st_rad", "st_raderr1", "st_raderr2", # stellar radius 
        "st_mass", "st_masserr1", "st_masserr2" # stellar mass
    ]
].copy()
display(ps)

/var/folders/j1/ycf8zrfn3qv2n37h22d0_6rw0000gp/T/ipykernel_26871/382473529.py:2: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  ps_raw = pd.read_csv(r"PS_2026.04.03_18.36.56.csv", skiprows = 292)

,rowid,pl_name,hostname,pl_letter,hd_name,hip_name,tic_id,gaia_dr2_id,gaia_dr3_id,default_flag,sy_snum,sy_pnum,sy_mnum,cb_flag,discoverymethod,disc_year,disc_refname,disc_pubdate,disc_locale,disc_facility,disc_telescope,disc_instrument,rv_flag,pul_flag,ptv_flag,tran_flag,ast_flag,obm_flag,micro_flag,etv_flag,ima_flag,dkin_flag,soltype,pl_controv_flag,pl_refname,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_orbsmax,pl_orbsmaxerr1,pl_orbsmaxerr2,pl_orbsmaxlim,pl_rade,pl_radeerr1,pl_radeerr2,pl_radelim,pl_radj,pl_radjerr1,pl_radjerr2,pl_radjlim,pl_masse,pl_masseerr1,pl_masseerr2,pl_masselim,pl_massj,pl_massjerr1,pl_massjerr2,pl_massjlim,pl_msinie,pl_msinieerr1,pl_msinieerr2,pl_msinielim,pl_msinij,pl_msinijerr1,pl_msinijerr2,pl_msinijlim,pl_cmasse,pl_cmasseerr1,pl_cmasseerr2,pl_cmasselim,pl_cmassj,pl_cmassjerr1,pl_cmassjerr2,pl_cmassjlim,pl_bmasse,pl_bmasseerr1,pl_bmasseerr2,pl_bmasselim,pl_bmassj,pl_bmassjerr1,pl_bmassjerr2,pl_bmassjlim,pl_bmassprov,pl_dens,pl_denserr1,pl_denserr2,pl_denslim,pl_orbeccen,pl_orbeccenerr1,pl_orbeccenerr2,pl_orbeccenlim,pl_insol,pl_insolerr1,pl_insolerr2,pl_insollim,pl_eqt,pl_eqterr1,pl_eqterr2,pl_eqtlim,pl_orbincl,pl_orbinclerr1,pl_orbinclerr2,pl_orbincllim,pl_tranmid,pl_tranmiderr1,pl_tranmiderr2,pl_tranmidlim,pl_tsystemref,ttv_flag,pl_imppar,pl_impparerr1,pl_impparerr2,pl_impparlim,pl_trandep,pl_trandeperr1,pl_trandeperr2,pl_trandeplim,pl_trandur,pl_trandurerr1,pl_trandurerr2,pl_trandurlim,pl_ratdor,pl_ratdorerr1,pl_ratdorerr2,pl_ratdorlim,pl_ratror,pl_ratrorerr1,pl_ratrorerr2,pl_ratrorlim,pl_occdep,pl_occdeperr1,pl_occdeperr2,pl_occdeplim,pl_orbtper,pl_orbtpererr1,pl_orbtpererr2,pl_orbtperlim,pl_orblper,pl_orblpererr1,pl_orblpererr2,pl_orblperlim,pl_rvamp,pl_rvamperr1,pl_rvamperr2,pl_rvamplim,pl_projobliq,pl_projobliqerr1,pl_projobliqerr2,pl_projobliqlim,pl_trueobliq,pl_trueobliqerr1,pl_trueobliqerr2,pl_trueobliqlim,st_refname,st_spectype,st_teff,st_tefferr1,st_tefferr2,st_tefflim,st_rad,st_raderr1,st_raderr2,st_radlim,st_mass,st_masserr1,st_masserr2,st_masslim,st_met,st_meterr1,st_meterr2,st_metlim,st_metratio,st_lum,st_lumerr1,st_lumerr2,st_lumlim,st_logg,st_loggerr1,st_loggerr2,st_logglim,st_age,st_ageerr1,st_ageerr2,st_agelim,st_dens,st_denserr1,st_denserr2,st_denslim,st_vsin,st_vsinerr1,st_vsinerr2,st_vsinlim,st_rotp,st_rotperr1,st_rotperr2,st_rotplim,st_radv,st_radverr1,st_radverr2,st_radvlim,sy_refname,rastr,ra,decstr,dec,glat,glon,elat,elon,sy_pm,sy_pmerr1,sy_pmerr2,sy_pmra,sy_pmraerr1,sy_pmraerr2,sy_pmdec,sy_pmdecerr1,sy_pmdecerr2,sy_dist,sy_disterr1,sy_disterr2,sy_plx,sy_plxerr1,sy_plxerr2,sy_bmag,sy_bmagerr1,sy_bmagerr2,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_jmag,sy_jmagerr1,sy_jmagerr2,sy_hmag,sy_hmagerr1,sy_hmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_umag,sy_umagerr1,sy_umagerr2,sy_gmag,sy_gmagerr1,sy_gmagerr2,sy_rmag,sy_rmagerr1,sy_rmagerr2,sy_imag,sy_imagerr1,sy_imagerr2,sy_zmag,sy_zmagerr1,sy_zmagerr2,sy_w1mag,sy_w1magerr1,sy_w1magerr2,sy_w2mag,sy_w2magerr1,sy_w2magerr2,sy_w3mag,sy_w3magerr1,sy_w3magerr2,sy_w4mag,sy_w4magerr1,sy_w4magerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2,sy_icmag,sy_icmagerr1,sy_icmagerr2,sy_tmag,sy_tmagerr1,sy_tmagerr2,sy_kepmag,sy_kepmagerr1,sy_kepmagerr2,rowupdate,pl_pubdate,releasedate,pl_nnotes,st_nphot,st_nrvc,st_nspec,pl_nespec,pl_ntranspec,pl_ndispec
0,1,11 Com b,11 Com,b,HD 107383,HIP 60202,TIC 72437047,Gaia DR2 3946945413106333696,Gaia DR3 3946945413106333696,1,2,1,0,0,Radial Velocity,2007.0,<a refstr=LIU_ET_AL__2008 href=https://ui.adsa...,2008-01,Ground,Xinglong Station,2.16 m Telescope,Coude Echelle Spectrograph,1,0,0,0,0,0,0,0,0,0,Published Confirmed,0,<a refstr=TENG_ET_AL__2023 href=https://ui.ads...,323.21000,0.06,-0.05,0.0,1.178,0.000,0.000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4914.898486,39.092894,-39.728551,0.0,15.464,0.123,-0.125,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4914.898486,39.092894,-39.728551,0.0,15.464,0.123,-0.125,0.0,Msini,NaN,NaN,NaN,NaN,0.238,0.007,-0.007,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,JD,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2454519.4,1.5,-1.6,0.0,91.33,1.7,-1.8,0.0,288.63,2.39,-2.37,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<a refstr=TENG_ET_AL__2023 href=https://ui.ads...,G8 III,4874.00,NaN,NaN,0.0,13.760000,2.850000,-2.450000,0.0,2.090000,0.640000,-0.630000,0.0,-0.2600,0.1000,-0.1000,0.0,[Fe/H],1.97823,0.18002,-0.15868,0.0,2.450000,0.080000,-0.080000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,12h20m42.91s,185.178779,+17d47m35.71s,17.793252,78.28058,264.13775,18.33392,177.41790,140.383627,0.301395,-0.301395,-109.24100,0.316107,-0.316107,88.1701,0.277297,-0.277297,93.1846,1.92380,-1.92380,10.71040,0.219739,-0.219739,5.726,0.017,-0.017,4.72307,0.023,-0.023,2.943,0.334,-0.334,2.484,0.268,-0.268,2.282,0.346,-0.346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.639,NaN,NaN,0.732,NaN,NaN,2.358,0.010,-0.010,2.270,0.018,-0.018,4.44038,0.003848,-0.003848,NaN,NaN,NaN,3.83790,0.0071,-0.0071,NaN,NaN,NaN,2023-09-19,2023-08,2023-09-19,2,1,2,0,0,0,0
1,2,11 Com b,11 Com,b,HD 107383,HIP 60202,TIC 72437047,Gaia DR2 3946945413106333696,Gaia DR3 3946945413106333696,0,2,1,0,0,Radial Velocity,2007.0,<a refstr=LIU_ET_AL__2008 href=https://ui.adsa...,2008-01,Ground,Xinglong Station,2.16 m Telescope,Coude Echelle Spectrograph,1,0,0,0,0,0,0,0,0,0,Published Confirmed,0,<a refstr=LIU_ET_AL__2008 href=https://ui.adsa...,326.03000,0.32,-0.32,0.0,1.290,0.050,-0.050,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6165.600000,476.700000,-476.700000,0.0,19.400,1.500,-1.500,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6165.600000,476.700000,-476.700000,0.0,19.400,1.500,-1.500,0.0,Msini,NaN,NaN,NaN,NaN,0.231,0.005,-0.005,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2452899.6,1.6,-1.6,0.0,94.80,1.5,-1.5,0.0,302.80,2.60,-2.60,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<a refstr=LIU_ET_AL__2008 href=https://ui.adsa...,G8 III,4742.00,100.00,-100.00,0.0,19.000000,2.000000,-2.000000,0.0,2.700000,0.300000,-0.300000,0.0,-0.3500,0.0900,-0.0900,0.0,[Fe/H],2.24300,0.07100,-0.08500,0.0,2.310000,0.100000,-0.100000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.20,1.0,-1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,12h20m42.91s,185.178779,+17d47m35.71s,17.793252,78.28058,264.13775,18.33392,177.41790,140.383627,0.301395,-0.301395,-109.24100,0.316107,-0.316107,88.1701,0.277297,-0.277297,93.1846,1.92380,-1.92380,10.71040,0.219739,-0.219739,5.726,0.017,-0.017,4.72307,0.023,-0.023,2.943,0.334,-0.334,2.484,0.268,-0.268,2.282,0.346,-0.346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.639,NaN,NaN,0.732,NaN,NaN,2.358,0.010,-0.010,2.270,0.018,-0.018,4.44038,0.003848,-0.003848,NaN,NaN,NaN,3.83790,0.0071,-0.0071,NaN,NaN,NaN,2014-05-14,2008-01,2014-05-14,2,1,2,0,0,0,0
2,3,11 Com b,11 Com,b,HD 107383,HIP 60202,TIC 72437047,Gaia DR2 3946945413106333696,Gaia DR3 3946945413106333696,0,2,1,0,0,Radial Velocity,2007.0,<a refstr=LIU_ET_AL__2008 href=https://ui.adsa...,2008-01,Ground,Xinglong Station,2.16 m Telescope,Coude Echelle Spectrograph,1,0,0,0,0,0,0,0,0,0,Published Confirmed,0,<a refstr=KUNITOMO_ET_AL__2011 href=https://ui...,NaN,NaN,NaN,NaN,1.210,0.060,-0.050,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5434.700000,540.300000,-413.200000,0.0,17.100,1.700,-1.300,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5434.700000,540.300000,-413.200000,0.0,17.100,1.700,-1.300,0.0,Msini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<a refstr=KUNITOMO_ET_AL__2011 href=https://ui...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.600000,0.400000,-0.300000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,12h20m42.91s,185.178779,+17d47m35.71s,17.793252,78.28058,264.13775,18.33392,177.41790,140.383627,0.301395,-0.301395,-109.24100,0.316107,-0.316107,88.1701,0.277297,-0.277297,93.1846,1.92380,-1.92380,10.71040,0.219739,-0.219739,5.726,0.017,-0.017,4.72307,0.023,-0.023,2.943,0.334,-0.334,2.484,0.268,-0.268,2.282,0.346,-0.346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.639,NaN,NaN,0.732,NaN,NaN,2.358,0.010,-0.010,2.270,0.018,-0.018,4.44038,0.003848,-0.003848,NaN,NaN,NaN,3.83790,0.0071,-0.0071,NaN,NaN,NaN,2014-07-23,2011-08,2014-07-23,2,1,2,0,0,0,0
3,4,11 UMi b,11 UMi,b,HD 136726,HIP 74793,TIC 230061010,Gaia DR2 1696798367260229376,Gaia DR3 1696798367260229376,0,1,1,0,0,Radial Velocity,2009.0,<a refstr=DOLLINGER_ET_AL__2009 href=https://u...,2009-10,Ground,Thueringer Landessternwarte Tautenburg,2.0 m Alfred Jensch Telescope,Coude Echelle Spectrograph,1,0,0,0,0,0,0,0,0,0,Published Confirmed,0,<a refstr=KUNITOMO_ET_AL__2011 href=https://ui...,NaN,NaN,NaN,NaN,1.510,0.060,-0.050,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3432.400000,381.400000,-413.200000,0.0,10.800,1.200,-1.300,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3432.400000,381.400000,-413.200000,0.0,10.800,1.200,-1.300,0.0,Msini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<a refstr=KUNITOMO_ET_AL__2011 href=https://ui...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.700000,0.400000,-0.300000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,15h17m05.90s,229.274595,+71d49m26.19s,71.823943,41.04437,108.71900,74.95821,141.64312,10.679019,0.218806,-0.218806,3.42996,0.231822,-0.231822,10.1132,0.217259,-0.217259,125.3210,1.97650,-1.97650,7.95388,0.124857,-0.124857,6.382,0.045,-0.045,5.01300,0.005,-0.005,2.876,0.230,-0.230,2.091,0.194,-0.194,1.939,0.270,-0.270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.290,NaN,NaN,0.143,NaN,NaN,1.894,0.012,-0.012,1.787,0.013,-0.013,4.56216,0.003903,-0.003903,NaN,NaN,NaN,3.82294,0.0075,-0.0075,NaN,NaN,NaN,2018-04-25,2011-08,2014-07-23,0,1,1,0,0,0,0
4,5,11 UMi b,11 UMi,b,HD 136726,HIP 74793,TIC 230061010,Gaia DR2 1696798367260229376,Gaia DR3 1696798367260229376,1,1,1,0,0,Radial Velocity,2009.0,<a refstr=DOLLINGER_ET_AL__2009 href=https://u...,2009-10,Ground,Thueringer Landessternwarte Tautenburg,2.0 m Alfred Jensch Telescope,Coude Echelle Spectrograph,1,0,0,0,0,0,0,0,0,0,Published Confirmed,0,<a refstr=STASSUN_ET_AL__2017 href=https://ui....,516.21997,3.20,-3.20,0.0,1.530,0.070,-0.070,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4684.814200,794.575000,-794.575000,0.0,14.740,2.500,-2.500,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4684.814200,794.575000,-794.575000,0.0,14.740,2.500,-2.500,0.0,Msini,NaN,NaN,NaN,NaN,0.080,0.030,-0.030,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189.70,7.20,-7.20,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<a refstr=STASSUN_ET_AL__2017 href=https://ui....,NaN,4213.00,46.00,-46.00,0.0,29.790000,2.840000,-2.840000,0.0,2.780000,0.690000,-0.690000,0.0,-0.0200,NaN,NaN,0.0,[Fe/H],NaN,NaN,NaN,NaN,1.930000,0.070000,-0.070000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,15h17m05.90s,229.274595,+71d49m26.19s,71.823943,41.04437,108.71900,74.95821,141.64312,10.679019,0.218806,-0.218806,3.42996,0.231822,-0.231822,10.1132,0.217259,-0.217259,125.3210,1.97650,-1.97650,7.95388,0.124857,-0.124857,6.382,0.045,-0.045,5.01300,0.005,-0.005,2.876,0.230,-0.230,2.091,0.194,-0.194,1.939,0.270,-0.270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.290,NaN,NaN,0.143,NaN,NaN,1.894,0.012,-0.012,1.787,0.013,-0.013,4.56216,0.003903,-0.003903,NaN,NaN,NaN,3.82294,0.0075,-0.0075,NaN,NaN,NaN,2018-09-04,2017-03,2018-09-06,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39532,39533,ups And d,ups And,d,HD 9826,HIP 7513,TIC 189576919,Gaia DR2 348020448377061376,Gaia DR3 348020482735930112,0,2,3,0,0,Radial Velocity,1999.0,<a refstr=BUTLER_ET_AL__1999 href=https://ui.a...,1999-12,Ground,Multiple Observatories,Multiple Telescopes,Multiple Instruments,1,0,0,0,0,0,0,0,0,0,Published Confirmed,0,<a refstr=ROSENTHAL_ET_AL__2021 href=https://u...,1282.41000,0.93,-0.94,0.0,2.517,0.026,-0.027,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1303.096469,31.782841,-31.782841,0.0,4.100,0.100,-0.100,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1303.096469,31.782841,-31.782841,0.0,4.100,0.100,-0.100,0.0,Msini,NaN,NaN,NaN,NaN,0.294,0.011,-0.012,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2453360.6,8.6,-8.5,0.0,BJD,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.80,2.5,-2.4,0.0,67.51,0.92,-0.89,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<a refstr=ROSENTHAL_ET_AL__2021 href=https://u...,NaN,6156.77,112.16,-112.16,0.0,1.622479,0.038881,-0.038881,0.0,1.294197,0.041225,-0.041225,0.0,0.1215,0.0626,-0.0626,0.0,[Fe/H],NaN,NaN,NaN,NaN,4.125176,0.024844,-0.024844,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,01h36m47.60s,24.198353,+41d24m13.73s,41.403815,-20.66791,132.00045,28.97913,38.54477,419.857418,0.539278,-0.539278,-172.24800,0.522126,-0.522126,-382.8980,0.542683,-0.542683,13.4054,0.06350,-0.06290,74.57110,0.349118,-0.349118,4.625,0.021,-0.021,4.09565,0.023,-0.023,3.175,0.210,-0.210,2.957,0.178,-0.178,2.859,0.274,-0.274,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.98687,0.008937,-0.008937,NaN,NaN,NaN,3.61370,2.1920,-2.1920,NaN,NaN,NaN,2021-09-20,2021-07,2021-09-20,5,1,10,1,0,0,0
39533,39534,ups Leo b,ups Leo,b,NaN,NaN,TIC 49430557,Gaia DR2 3794167001116433152,Gaia DR3 3794167001116704000,1,1,1,0,0,Radial Velocity,2021.0,<a refstr=TENG_ET_AL__2021 href=https://ui.ads...,2021-12,Ground,Okayama Astrophysical Observatory,1.88 m Telescope,HIDES Echelle Spectrograph,1,0,0,0,0,0,0,0,0,0,Published Confirmed,0,<a refstr=TENG_ET_AL__2021 href=https://ui.ads...,385.20000,2.80,-1.30,0.0,1.180,0.110,-0.320,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162.092488,19.069704,-82.635386,0.0,0.510,0.060,-0.260,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162.092488,19.069704,-82.635386,0.0,0.510,0.060,-0.260,0.0,Msini,NaN,NaN,NaN,NaN,0.320,0.134,-0.218,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,JD,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2455279.6,27.9,-34.2,0.0,131.00,36.0,-31.0,0.0,11.70,1.70,-1.60,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<a refstr=TENG_ET_AL__2021 href=https://ui.ads...,G9 III,4836.00,NaN,NaN,0.0,11.220000,3.150000,-0.450000,0.0,1.480000,0.900000,-0.380000,0.0,-0.2000,0.0900,-0.0800,0.0,[Fe/H],1.80003,0.22062,-0.05480,0.0,2.460000,0.090000,-0.090000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.78,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,11h36m56.93s,174.237219,-00d49m24.83s,-0.823564,56.79861,267.26323,-3.04521,175.03272,42.335113,0.433739,-0.433739,2.77905,0.504088,-0.504088,42.2438,0.433410,-0.433410,52.5973,0.92720,-0.89630,18.99390,0.326940,-0.326940,5.296,0.017,-0.017,4.30490,0.023,-0.023,2.781,0.306,-0.306,2.267,0.218,-0.218,2.184,0.248,-0.248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.065,NaN,NaN,0.147,NaN,NaN,2.059,0.014,-0.014,1.940,0.022,-0.022,4.03040,0.008513,-0.008513,NaN,NaN,NaN,3.44620,2.0505,-2.0505,NaN,NaN,NaN,2022-01-10,2021-12,2022-01-10,0,0,0,0,0,0,0
39534,39535,xi Aql b,xi Aql,b,HD 188310,HIP 97938,TIC 375464367,Gaia DR2 4298361114750843904,Gaia DR3 4298361114753012992,0,1,1,0,0,Radial Velocity,2007.0,<a refstr=SATO_ET_AL__2008 href=https://ui.ads...,2008-06,Ground,Okayama Astrophysical Observatory,1.88 m Telescope,HIDES Echelle Spectrograph,1,0,0,0,0,0,0,0,0,0,Published Confirmed,0,<a refstr=KUNITOMO_ET_AL__2011 href=https://ui...,NaN,NaN,NaN,NaN,0.580,0.020,-0.030,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,642.000000,63.600000,-63.600000,0.0,2.020,0.200,-0.200,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,642.000000,63.600000,-63.600000,0.0,2.020,0.200,-0.200,0.0,Msini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<a refstr=KUNITOMO_ET_AL__2011 href=https://ui...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.400000,0.200000,-0.200000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,19h54m14.99s,298.562449,+08d27m39.98s,8.461105,-9.85535,47.81277,28.72199,302.62958,129.341395,0.295758,-0.295758,101.17700,0.316633,-0.316633,-80.5755,0.259453,-0.259453,56.1858,0.55975,-0.55975,17.77250,0.175959,-0.175959,5.761,0.017,-0.017,4.70964,0.023,-0.023,2.852,0.220,-0.220,2.367,0.174,-0.174,2.171,0.220,-0.220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.633,NaN,NaN,0.569,NaN,NaN,2.325,0.015,-0.015,2.216,0.020,-0.020,4.42501,0.003837,-0.003837,NaN,NaN,NaN,3.81440,0.0072,-0.0072,NaN,NaN,NaN,2014-07-23,2011-08,2014-07-23,1,1,1,0,0,0,0

,pl_name,hostname,default_flag,pl_rade,pl_radeerr1,pl_radeerr2,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_eqt,pl_eqterr1,pl_eqterr2,st_teff,st_tefferr1,st_tefferr2,st_rad,st_raderr1,st_raderr2,st_mass,st_masserr1,st_masserr2
0,11 Com b,11 Com,1,NaN,NaN,NaN,323.21000,0.06,-0.05,NaN,NaN,NaN,4874.00,NaN,NaN,13.760000,2.850000,-2.450000,2.090000,0.640000,-0.630000
1,11 Com b,11 Com,0,NaN,NaN,NaN,326.03000,0.32,-0.32,NaN,NaN,NaN,4742.00,100.00,-100.00,19.000000,2.000000,-2.000000,2.700000,0.300000,-0.300000
2,11 Com b,11 Com,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.600000,0.400000,-0.300000
3,11 UMi b,11 UMi,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.700000,0.400000,-0.300000
4,11 UMi b,11 UMi,1,NaN,NaN,NaN,516.21997,3.20,-3.20,NaN,NaN,NaN,4213.00,46.00,-46.00,29.790000,2.840000,-2.840000,2.780000,0.690000,-0.690000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39532,ups And d,ups And,0,NaN,NaN,NaN,1282.41000,0.93,-0.94,NaN,NaN,NaN,6156.77,112.16,-112.16,1.622479,0.038881,-0.038881,1.294197,0.041225,-0.041225
39533,ups Leo b,ups Leo,1,NaN,NaN,NaN,385.20000,2.80,-1.30,NaN,NaN,NaN,4836.00,NaN,NaN,11.220000,3.150000,-0.450000,1.480000,0.900000,-0.380000
39534,xi Aql b,xi Aql,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.400000,0.200000,-0.200000
39535,xi Aql b,xi Aql,0,NaN,NaN,NaN,136.75000,0.25,-0.25,NaN,NaN,NaN,4780.00,30.00,-30.00,12.000000,NaN,NaN,2.200000,NaN,NaN
39536,xi Aql b,xi Aql,1,NaN,NaN,NaN,136.97000,0.11,-0.18,NaN,NaN,NaN,4841.00,NaN,NaN,10.860000,0.440000,-1.050000,1.740000,0.210000,-0.280000

In [3]:
# convert to numeric
numeric_cols = [
        "pl_rade", "pl_radeerr1", "pl_radeerr2", 
        "pl_orbper", "pl_orbpererr1", "pl_orbpererr2", 
        "pl_eqt", "pl_eqterr1", "pl_eqterr2", 
        "st_teff", "st_tefferr1", "st_tefferr2", 
        "st_rad", "st_raderr1", "st_raderr2", 
        "st_mass", "st_masserr1", "st_masserr2"
]
for col in numeric_cols:
    ps[col] = pd.to_numeric(ps[col], errors = "coerce")
print(ps.dtypes)

# determine missing values
required_cols = [
    "pl_rade",
    "pl_orbper",
    "pl_eqt",
    "st_teff",
    "st_rad",
    "st_mass"
]
print("\nMissing Values:")
print(ps[required_cols].isnull().sum())
print("\nPercent Missing:")
print((ps[required_cols].isnull().sum() / len(ps) * 100).round(2))

# drop missing values in required fields
rows_before = ps.shape[0]
ps = ps.dropna(subset = required_cols).copy()
rows_after = ps.shape[0]
print("\nRows Before Dropping Missing Values:", rows_before)
print("Rows After Dropping Missing Values:", rows_after)
print("Rows Removed:", rows_before - rows_after)

# keep only default parameter rows
print("\nDefault Flag Distribution:")
print(ps["default_flag"].value_counts(dropna=False))
ps = ps[ps["default_flag"] == 1].copy()

pl_name           object
hostname          object
default_flag       int64
pl_rade          float64
pl_radeerr1      float64
pl_radeerr2      float64
pl_orbper        float64
pl_orbpererr1    float64
pl_orbpererr2    float64
pl_eqt           float64
pl_eqterr1       float64
pl_eqterr2       float64
st_teff          float64
st_tefferr1      float64
st_tefferr2      float64
st_rad           float64
st_raderr1       float64
st_raderr2       float64
st_mass          float64
st_masserr1      float64
st_masserr2      float64
dtype: object

Missing Values:
pl_rade      12329
pl_orbper     3333
pl_eqt       22185
st_teff       3558
st_rad        3374
st_mass       6212
dtype: int64

Percent Missing:
pl_rade      31.18
pl_orbper     8.43
pl_eqt       56.11
st_teff       9.00
st_rad        8.53
st_mass      15.71
dtype: float64

Rows Before Dropping Missing Values: 39537
Rows After Dropping Missing Values: 15575
Rows Removed: 23962

Default Flag Distribution:
default_flag
0    14092
1     1483
Name: count, dtype: int64

In [4]:
# create average uncertainty magnitude from asymmetric bounds
ps["pl_rade_unc"] = (ps["pl_radeerr1"].abs() + ps["pl_radeerr2"].abs()) / 2
ps["pl_orbper_unc"] = (ps["pl_orbpererr1"].abs() + ps["pl_orbpererr2"].abs()) / 2
ps["pl_eqt_unc"] = (ps["pl_eqterr1"].abs() + ps["pl_eqterr2"].abs()) / 2
ps["st_teff_unc"] = (ps["st_tefferr1"].abs() + ps["st_tefferr2"].abs()) / 2
ps["st_rad_unc"] = (ps["st_raderr1"].abs() + ps["st_raderr2"].abs()) / 2
ps["st_mass_unc"] = (ps["st_masserr1"].abs() + ps["st_masserr2"].abs()) / 2

# if uncertainty missing, fill with 0
ps["pl_rade_unc"] = ps["pl_rade_unc"].fillna(0)
ps["pl_orbper_unc"] = ps["pl_orbper_unc"].fillna(0)
ps["pl_eqt_unc"] = ps["pl_eqt_unc"].fillna(0)
ps["st_teff_unc"] = ps["st_rad_unc"].fillna(0)
ps["st_rad_unc"] = ps["st_rad_unc"].fillna(0)
ps["st_mass_unc"] = ps["st_mass_unc"].fillna(0)

In [5]:
# create proxy habitability label
ps["proxy_habitable"] = np.where(
    (ps["pl_rade"] <= 1.6) &
    (ps["pl_eqt"] >= 180) &
    (ps["pl_eqt"] <= 310),
    1,
    0
)
display(ps[["pl_name", "pl_rade", "pl_eqt", "proxy_habitable"]])

                pl_name    pl_rade  pl_eqt  proxy_habitable
188            AU Mic b   4.790000   554.8                0
205            AU Mic c   2.790000   424.7                0
253        BD-14 3065 b  21.590000  2001.0                0
274    CFHTWIR-Oph 98 b  20.848704  1800.0                0
284           CoRoT-1 b  16.700000  1898.0                0
...                 ...        ...     ...              ...
39302        Wolf 503 b   2.043000   790.0                0
39343            XO-3 b  14.795855  1890.0                0
39368            XO-5 b  12.780000  1230.0                0
39381            XO-6 b  23.202630  1577.0                0
39382            XO-7 b  15.389957  1743.0                0

[1483 rows x 4 columns]

In [6]:
# inspect class balance
print(ps["proxy_habitable"].value_counts())
print("\nClass proportions:")
print(ps["proxy_habitable"].value_counts(normalize=True).round(4))

# summary stats
ps[
    [
        "pl_rade", "pl_orbper", "pl_eqt",
        "st_teff", "st_rad", "st_mass",
        "pl_rade_unc", "pl_orbper_unc", "pl_eqt_unc",
        "st_teff_unc", "st_rad_unc", "st_mass_unc",
        "proxy_habitable"
    ]
].describe()

proxy_habitable
0    1474
1       9
Name: count, dtype: int64

Class proportions:
proxy_habitable
0    0.9939
1    0.0061
Name: proportion, dtype: float64

,pl_rade,pl_orbper,pl_eqt,st_teff,st_rad,st_mass,pl_rade_unc,pl_orbper_unc,pl_eqt_unc,st_teff_unc,st_rad_unc,st_mass_unc,proxy_habitable
count,1483.000000,1.483000e+03,1483.000000,1483.000000,1483.000000,1483.000000,1483.000000,1483.000000,1483.000000,1483.000000,1483.000000,1483.000000,1483.000000
mean,6.936455,5.442474e+03,1027.826864,5208.695617,1.011507,0.909133,0.401193,317.758339,26.055037,0.046797,0.046797,0.046134,0.006069
std,5.745120,2.087778e+05,516.547857,998.864427,0.509152,0.320561,0.699771,12204.723353,28.885643,0.099890,0.099890,0.034914,0.077692
min,0.309800,2.792210e-01,124.700000,2320.000000,0.013100,0.014700,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.100000,3.148269e+00,633.500000,4640.000000,0.695000,0.719000,0.100000,0.000003,10.000000,0.015000,0.015000,0.023000,0.000000
50%,3.650000,5.113981e+00,930.000000,5455.000000,0.920000,0.914000,0.200000,0.000014,18.180000,0.026000,0.026000,0.040000,0.000000
75%,12.110000,1.234230e+01,1387.000000,5890.000000,1.281590,1.103000,0.448360,0.000110,32.000000,0.049500,0.049500,0.060000,0.000000
max,32.600000,8.040000e+06,4050.000000,10170.000000,6.300000,2.520000,9.330000,470000.000000,400.000000,2.295000,2.295000,0.358500,1.000000

In [7]:
# export cleaned data
ps.to_csv("exoplanet_volatility_cleaned.csv", index = False)